### ISSUE TITLE
Use gradle-plugin's built in filtering for jmeter plugins?

### ISSUE THREAD

**Issue by foragerr** [djangofan/launch-jmeter#1]
The gradle-plugin implements its own jmeter-classpath filtering based on plugin name. ref:
https://github.com/kulya/jmeter-gradle-plugin/blob/master/src/main/groovy/com/github/kulya/gradle/plugins/jmeter/JmeterAbstractTask.groovy#L118 lines 118 - 123

I feel like you don't have to do the filtering yourself. Please see this change: https://github.com/foragerr/launch-jmeter/commit/234f55fcdc5449785b8bd08afc91766fbab5ab6f

I'm not familiar enough with the plugins myself, can you please verify if they load correctly this way?

**Comment by djangofan** [comment]
I just tried your suggestion.   I appears that what you suggest does work for all the 3rd party libs EXCEPT for the jmeter-plugin libs.   It looks to me like the wildcard matcher on just the  'jmeter-plugin-'  option isn't working.    

1. For example, when I start my project with your suggestion, I do see the Groovy options are available. 
2.  This code is runnable: 
import org.apache.commons.lang3.time.StopWatch;
StopWatch sw = new StopWatch();
sw.start();
log.info("Start time: " + sw.getStartTime() );  

Is it possible you can help figure out the 'jmeter-plugin' ?   We know it should work, based on the example I gave.  I bet that it is just a matter of fixing a small bug.

**Comment by foragerr** [comment]
https://github.com/kulya/jmeter-gradle-plugin/blob/master/src/main/groovy/com/github/kulya/gradle/plugins/jmeter/JmeterAbstractTask.groovy#L120

is using the matching pattern `matches("^.*" + plugin + "\$")` I realize now, that means endingIn() rather than contains(). The pattern should probably work with wildcards though. I would try `"jmeter-plugins.*"`
